import Head from "next/head";
import Header from "@/components/Header/Header";
import Mapscontainer from "@/components/Maps/Mapscontainer";
import Maps from "@/components/Maps/Maps";
import React, { useEffect } from "react";
import { StoreRoot, useStore } from "@/store";
import Hero from "@/components/Hero/Hero";
import InfoContainer from "@/components/Info/InfoContainer";
import Info from "@/components/Info/Info";

export default function Home() {
  const { handleRadius, centerPosition } = useStore() as StoreRoot;
  useEffect(() => {
    handleRadius(centerPosition);
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header title="London Parking" />
        <Hero />
        <InfoContainer>
          <Info />
        </InfoContainer>
        <Mapscontainer>
          <h1 className="text-2xl">Maps of Car Park in U.K</h1>
          <Maps />
        </Mapscontainer>
      </main>
    </>
  );
}
